<br />
<div class="row">
	<?php
	   if(!$this->isFinishToSave) {
	?>
	<div class="panel panel-default">
		<div class="panel-heading">Saisonplan anlegen</div>
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive" style="overflow: hidden">
				<form action="<?php echo $this->form->getAction(); ?>"
					method="<?php echo $this->form->getMethod(); ?>">
					<div class="form-group row">
						<div class="col-sm-2">
							<label class="col-form-label"
								style="padding-top: calc(.5rem - 1px * 2); padding-bottom: calc(.5rem - 1px * 2); margin-bottom: 0;">Saison</label>
						</div>
						<div class="col-sm-2">
							<?php echo $this->form->getElement('saison')->removeDecorator('label'); ?>
						</div>
						<div class="col-sm-8"></div>
					</div>
					<div class="form-group row">
						<div class="col-sm-2">
							<label class="col-form-label"
								style="padding-top: calc(.5rem - 1px * 2); padding-bottom: calc(.5rem - 1px * 2); margin-bottom: 0;">Spiel-Nr.</label>
						</div>
						<div class="col-sm-2">
							<label class="col-form-label"
								style="padding-top: calc(.5rem - 1px * 2); padding-bottom: calc(.5rem - 1px * 2); margin-bottom: 0;">Datum</label>
						</div>
						<div class="col-sm-3">
							<label class="col-form-label"
								style="padding-top: calc(.5rem - 1px * 2); padding-bottom: calc(.5rem - 1px * 2); margin-bottom: 0;">Heim</label>
						</div>
						<div class="col-sm-2"></div>
						<div class="col-sm-3">
							<label class="col-form-label"
								style="padding-top: calc(.5rem - 1px * 2); padding-bottom: calc(.5rem - 1px * 2); margin-bottom: 0;">Gast</label>
						</div>
					</div>
					<?php for ($fieldCount = 0; $fieldCount < $this->form->getCountOfDays(); $fieldCount ++) { ?>
					<div class="form-group row">
						<div class="col-sm-2">
							<?php echo $this->form->getElement('day' . $fieldCount)->removeDecorator('label'); ?>
						</div>
						<div class="col-sm-2">
							<?php echo $this->form->getElement('date' . $fieldCount)->removeDecorator('label'); ?>
						</div>
						<div class="col-sm-3">
							<?php echo $this->form->getElement('1team' . $fieldCount)->removeDecorator('label'); ?>
						</div>
						<div class="col-sm-2 text-center">
							<label class="col-form-label"
								style="padding-top: calc(.5rem - 1px * 2); padding-bottom: calc(.5rem - 1px * 2); margin-bottom: 0;">vs</label>
						</div>
						<div class="col-sm-3">
							<?php echo $this->form->getElement('2team' . $fieldCount)->removeDecorator('label'); ?>
						</div>
					</div>
        			<?php } ?>
        			<div class="form-group row">
						<div class="col-sm-3">
							<!-- TODO: ABBRECHEN-Button einfügen -->
						</div>
						<div class="col-sm-6"></div>
						<div class="col-sm-3">
							<?php echo $this->form->getElement('submit'); ?>
						</div>
					</div>
				</form>
				<?php #echo $this->form; ?>
				<div class="alert alert-danger" <?php echo $this->dangerMsgState; ?>>
					<?php echo $this->dangerMsg; ?>
				</div>
			</div>
			<!-- /.table-responsive -->
		</div>
		<!-- /.panel-body -->
	</div>
	<!-- /.panel -->
	<?php
	   } // ENDE:  !$this->isFinishToSave
	   else {
	?>
	<div class="panel panel-default">
		<div class="panel-heading">Saisonplan anlegen</div>
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive" style="overflow: hidden">
				<div class="alert alert-success" <?php echo $this->successMsgState; ?>>
					<?php echo $this->successMsg; ?>
				</div>
				<div class="alert alert-danger" <?php echo $this->dangerMsgState; ?>>
					<?php echo $this->dangerMsg; ?>
				</div>
			</div>
			<!-- /.table-responsive -->
		</div>
		<!-- /.panel-body -->
	</div>
	<!-- /.panel -->
	<?php
	   }
	?>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$(function () {
		$(".datepicker").datepicker({
			"dateFormat": "dd.mm.yy"
		});
	});
});
</script>