<br />
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">Saisonpl&auml;ne</div>
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive" style="overflow: hidden">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>#</th>
							<th>Saison</th>
							<th style="width: 200px;">Aktion</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($this->plans as $plan): ?>
						<tr>
							<td><?php echo $this->escape($plan->getSpielplan_id()) ?></td>
							<td><?php echo $this->escape($plan->getSaison()) ?></td>
							<td>
							<a href="<?php echo $this->url(array('controller'=>'saison','action' => 'view', 'planid' => $plan->getSpielplan_id()), 'default', true) ?>"><button type="button" class="btn btn-primary btn-circle btn-sm"><i class="fa fa-list"></i></button></a>
							<a href="<?php echo $this->url(array('controller'=>'saison','action' => 'edit', 'planid' => $plan->getSpielplan_id()), 'default', true) ?>"><button type="button" class="btn btn-warning btn-circle"><i class="fa fa-edit"></i></button></a>
							<!--
							<a href="<?php echo $this->url(array('controller'=>'saison','action' => 'delete', 'planid' => $plan->getSpielplan_id()), 'default', true) ?>"><button type="button" class="btn btn-danger btn-circle"><i class="fa fa-times"></i></button></a>
							-->
							</td>
						</tr>
						<?php endforeach ?>
					</tbody>
				</table>
				<div class="alert alert-danger" <?php echo $this->dangerMsgState; ?>>
					<?php echo $this->dangerMsg; ?>
				</div>
			</div>
			<!-- /.table-responsive -->
		</div>
		<!-- /.panel-body -->
	</div>
	<!-- /.panel -->
</div>