<br />
<div class="row">
	<div class="panel panel-default">
		<div class="panel-heading">Saisonplan anlegen</div>
		<!-- /.panel-heading -->
		<div class="panel-body">
			<div class="table-responsive">
				<?php
                    // TODO: put the "Weiter"-button on the right. not over whole screen
                ?>
				<?php echo $this->form; ?>
				<div class="alert alert-danger" <?php echo $this->dangerMsgState; ?>>
					<?php echo $this->dangerMsg; ?>
				</div>
			</div>
			<!-- /.table-responsive -->
		</div>
		<!-- /.panel-body -->
	</div>
	<!-- /.panel -->
</div>