<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Bitte anmelden</h3>
				</div>
				<div class="panel-body">
					<?php echo $this->form; ?>
					<div class="alert alert-danger" <?php echo $this->dangerMsgState; ?>>
					<?php echo $this->dangerMsg; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>