<?php
/*
 * TODO: create navigation from Zend_Navigation!
 */

// URLS
$url_index            = $this->url(array('controller'=>'index'), 'default', true);
$url_index_logout     = $this->url(array('controller'=>'index', 'action' => 'logout'), 'default', true);
$url_profil           = $this->url(array('controller'=>'profil'), 'default', true);
$url_settings         = $this->url(array('controller'=>'settings'), 'default', true);
$url_useroverview     = $this->url(array('controller'=>'useroverview'), 'default', true);
$url_useroverview_add = $this->url(array('controller'=>'useroverview','action' => 'add'), 'default', true);
$url_team             = $this->url(array('controller'=>'team'), 'default', true);
$url_team_add         = $this->url(array('controller'=>'team','action' => 'add'), 'default', true);

$url_saison           = $this->url(array('controller'=>'saison'), 'default', true);
$url_saison_view      = $this->url(array('controller'=>'saison','action' => 'view'), 'default', true);
$url_saison_all       = $this->url(array('controller'=>'saison','action' => 'all'), 'default', true);
$url_saison_prepare   = $this->url(array('controller'=>'saison','action' => 'prepare'), 'default', true);
$url_saison_add       = $this->url(array('controller'=>'saison','action' => 'add'), 'default', true);

$authentication = new Zend_Session_Namespace('Authentication');
$role = $authentication->role;
#$role = "player";
#$role = "coach";
if($role == 'admin') {
    $isPlayer = $isCoach = $isAdmin = true;
} else if($role == 'coach') {
    $isAdmin = false;
    $isPlayer = $isCoach = true;
} else {
    $isPlayer = $isCoach = $isAdmin = false;
}
?>
<div id="wrapper">
	<!-- Navigation -->
	<nav class="navbar navbar-default navbar-static-top" role="navigation"
		style="margin-bottom: 0">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?php echo $url_index; ?>">Freudenberg Tennis-Management</a>
		</div>
		<!-- /.navbar-header -->
		<ul class="nav navbar-top-links navbar-right">
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-envelope fa-fw"></i>
					<i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-messages">
					<li>
						<a href="#">
							<div>
								<strong>John Smith</strong>
								<span class="pull-right text-muted">
									<em>Yesterday</em>
								</span>
							</div>
							<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
						</a>
					</li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<strong>John Smith</strong> <span class="pull-right text-muted">
									<em>Yesterday</em>
								</span>
							</div>
							<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
								Pellentesque eleifend...</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<strong>John Smith</strong> <span class="pull-right text-muted">
									<em>Yesterday</em>
								</span>
							</div>
							<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
								Pellentesque eleifend...</div>
					</a></li>
					<li class="divider"></li>
					<li><a class="text-center" href="#"> <strong>Read All Messages</strong>
							<i class="fa fa-angle-right"></i>
					</a></li>
				</ul> <!-- /.dropdown-messages --></li>
			<!-- /.dropdown -->
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-tasks fa-fw"></i>
					<i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-tasks">
					<li><a href="#">
							<div>
								<p>
									<strong>Task 1</strong> <span class="pull-right text-muted">40%
										Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-success"
										role="progressbar" aria-valuenow="40" aria-valuemin="0"
										aria-valuemax="100" style="width: 40%">
										<span class="sr-only">40% Complete (success)</span>
									</div>
								</div>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<p>
									<strong>Task 2</strong> <span class="pull-right text-muted">20%
										Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-info" role="progressbar"
										aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"
										style="width: 20%">
										<span class="sr-only">20% Complete</span>
									</div>
								</div>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<p>
									<strong>Task 3</strong> <span class="pull-right text-muted">60%
										Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-warning"
										role="progressbar" aria-valuenow="60" aria-valuemin="0"
										aria-valuemax="100" style="width: 60%">
										<span class="sr-only">60% Complete (warning)</span>
									</div>
								</div>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<p>
									<strong>Task 4</strong> <span class="pull-right text-muted">80%
										Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-danger"
										role="progressbar" aria-valuenow="80" aria-valuemin="0"
										aria-valuemax="100" style="width: 80%">
										<span class="sr-only">80% Complete (danger)</span>
									</div>
								</div>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a class="text-center" href="#"> <strong>See All Tasks</strong>
							<i class="fa fa-angle-right"></i>
					</a></li>
				</ul> <!-- /.dropdown-tasks --></li>
			<!-- /.dropdown -->
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-bell fa-fw"></i>
					<i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-alerts">
					<li><a href="#">
							<div>
								<i class="fa fa-comment fa-fw"></i> New Comment <span
									class="pull-right text-muted small">4 minutes ago</span>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<i class="fa fa-twitter fa-fw"></i> 3 New Followers <span
									class="pull-right text-muted small">12 minutes ago</span>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<i class="fa fa-envelope fa-fw"></i> Message Sent <span
									class="pull-right text-muted small">4 minutes ago</span>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<i class="fa fa-tasks fa-fw"></i> New Task <span
									class="pull-right text-muted small">4 minutes ago</span>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a href="#">
							<div>
								<i class="fa fa-upload fa-fw"></i> Server Rebooted <span
									class="pull-right text-muted small">4 minutes ago</span>
							</div>
					</a></li>
					<li class="divider"></li>
					<li><a class="text-center" href="#"> <strong>See All Alerts</strong>
							<i class="fa fa-angle-right"></i>
					</a></li>
				</ul> <!-- /.dropdown-alerts --></li>
			<!-- /.dropdown -->
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-user fa-fw"></i>
					<i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-user">
					<li><a href="<?php echo $url_profil; ?>"><i class="fa fa-user fa-fw"></i> Profil</a></li>
					<li><a href="<?php echo $url_settings; ?>"><i class="fa fa-gear fa-fw"></i>
							Einstellungen</a></li>
					<li class="divider"></li>
					<li><a href="<?php echo $url_index_logout; ?>"><i class="fa fa-sign-out fa-fw"></i>
							Abmelden</a></li>
				</ul> <!-- /.dropdown-user -->
			</li>
			<!-- /.dropdown -->
		</ul>
		<!-- /.navbar-top-links -->

		<div class="navbar-default sidebar" role="navigation">
			<div class="sidebar-nav navbar-collapse">
				<ul class="nav" id="side-menu">
					<li class="sidebar-search">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Suchen...">
								<button class="btn btn-default btn-block" type="button">
									<i class="fa fa-search"></i>
								</button>
						</div> <!-- /input-group -->
						<div class="input-group">
							<select class="form-control">
								<option name="">Karl Reinhard</option>
								<option name="">Cedric Reinhard</option>
								<option name="">Jessica Reinhard</option>
								<option name="">Manfred Wunder</option>
								<option name="">Robin Brehm</option>
							</select>
							<span class="input-group-btn">
								<button class="btn btn-warning"><i class="fa fa-search"></i></button>
							</span>
						</div>
					</li>
					<li>
						<a href="<?php echo $url_index; ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
					</li>
					<li><a href="#"><i class="fa fa-table fa-fw"></i> Saisonplanung<span
							class="fa arrow"></span></a>
						<ul class="nav nav-second-level">
							<li><a href="<?php echo $url_saison_view . '/planid/'; ?>">Aktueller Saisonplan</a></li>
							<li><a href="<?php echo $url_saison_all; ?>">Saisonpl&auml;ne</a></li>
							<li <?php echo ($isAdmin) ? '' : 'class="hide"' ?>><a href="<?php echo $url_saison_prepare; ?>">Saisonplan anlegen</a></li>
						</ul> <!-- /.nav-second-level --></li>
					<li><a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Team<span
							class="fa arrow"></span></a>
						<ul class="nav nav-second-level">
							<li><a href="<?php echo $url_team; ?>">Team ansehen</a></li>
							<li><a href="#1">Aktueller Spielplan</a></li>
							<li><a href="#2">Spielplan</a></li>
							<li><a href="<?php echo $url_team_add; ?>">Spieler anlegen</a></li>
						</ul> <!-- /.nav-second-level --></li>
					<li <?php echo ($isAdmin) ? '' : 'class="hide"' ?>><a href="#"><i class="fa fa-bar-chart-o fa-fw"></i>
							Benutzerverwaltung<span class="fa arrow"></span></a>
						<ul class="nav nav-second-level">
							<li><a
								href="<?php echo $url_useroverview; ?>">Benutzer&uuml;bersicht</a></li>
							<li><a
								href="<?php echo $url_useroverview_add; ?>">Benutzer
									anlegen</a></li>
						</ul> <!-- /.nav-second-level --></li>
					<li class="hide"><a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level
							Dropdown<span class="fa arrow"></span></a>
						<ul class="nav nav-second-level">
							<li><a href="#">Second Level Item</a></li>
							<li><a href="#">Second Level Item</a></li>
							<li><a href="#">Third Level <span class="fa arrow"></span></a>
								<ul class="nav nav-third-level">
									<li><a href="#">Third Level Item</a></li>
									<li><a href="#">Third Level Item</a></li>
									<li><a href="#">Third Level Item</a></li>
									<li><a href="#">Third Level Item</a></li>
								</ul> <!-- /.nav-third-level --></li>
						</ul> <!-- /.nav-second-level --></li>
				</ul>
			</div>
			<!-- /.sidebar-collapse -->
		</div>
		<!-- /.navbar-static-side -->
	</nav>
	<div id="page-wrapper">
    	<?php echo $this->layout()->content; ?>
    </div>
	<!-- /#page-wrapper -->
</div>
<!-- /#wrapper -->